/* 3381:10 */
define({
    CREATED: "created",
    STATE_CHANGE: "state-change",
    DESTROYED: "destroyed",
    PLAY: "play",
    PLAY_START: "play-start",
    PLAY_RESUME: "play-resume",
    METADATA: "metadata",
    PAUSE: "pause",
    FINISH: "finish",
    RESET: "reset",
    SEEK: "seek",
    SEEKED: "seeked",
    GEO_BLOCKED: "geo_blocked",
    BUFFERRING_START: "buffering_start",
    BUFFERRING_END: "buffering_end",
    AUDIO_ERROR: "audio_error",
    TIME: "time",
    NO_STREAMS: "no_streams",
    STREAMS: "streams",
    NO_PROTOCOL: "no_protocol",
    NO_CONNECTION: "no_connection",
    API_FAILURE: "api_failure",
    REQUEST_FAILURE: "request_failure",
    REGISTERED: "registered",
    ONLINE: "online",
    OFFLINE: "offline"
})