define([], function(){
    return {
        HTML5_AUDIO_ABORTED: "HTML5_AUDIO_ABORTED",
        HTML5_AUDIO_NETWORK: "HTML5_AUDIO_NETWORK",
        HTML5_AUDIO_DECODE: "HTML5_AUDIO_DECODE",
        HTML5_AUDIO_SRC_NOT_SUPPORTED: "HTML5_AUDIO_SRC_NOT_SUPPORTED",
        HTML5_AUDIO_ENDED_EARLY: "HTML5_AUDIO_ENDED_EARLY",
        HTML5_AUDIO_OVERRUN: "HTML5_AUDIO_OVERRUN",
        MSE_BAD_OBJECT_STATE: "MSE_BAD_OBJECT_STATE",
        MSE_NOT_SUPPORTED: "MSE_NOT_SUPPORTED",
        MSE_MP3_NOT_SUPPORTED: "MSE_MP3_NOT_SUPPORTED",
        MSE_HLS_NOT_VALID_PLAYLIST: "MSE_HLS_NOT_VALID_PLAYLIST",
        MSE_HLS_PLAYLIST_NOT_FOUND: "MSE_HLS_PLAYLIST_NOT_FOUND",
        MSE_HLS_SEGMENT_NOT_FOUND: "MSE_HLS_SEGMENT_NOT_FOUND"
    }
});